var pageMap = {
	"/" : "consumer|dashboard",
	"/home" : "consumer|dashboard",
	"/activation" : "activation|challenge",
    "/activation/credentials" : "activation|credentials",
    "/activation/failure" : "activation|failure",
    "/activation/request" : "activation|request",
    "/activation/request/success" : "activation|request|success",
    "/business" : "business|dashboard",
    "/claimproducts" : "claimproducts|confirm",
    "/claimproducts/failure" : "claimproducts|failure",
    "/manage" : "manage|details",
    "/manage/contactnumber/add/success" : "postloginaction|contactnumber|add|success",
    "/manage/contactnumber/add": "manage|contactnumber|add",
    "/manage/contactnumber/change" : "manage|contactnumber|change",
    "/manage/password/change" : "manage|password|change",
    "/manage/password/change/success" : "postloginaction|password|change|success",
    "/openid/postloginaction/manage/password/expired": "novum|manage|password|expired",
    "/openid/postloginaction/manage/password/change": "novum|manage|password|change",
    "/openid/postloginaction/manage/password/change/success": "novum|manage|password|change|success",
    "/manage/password/expired" : "postloginaction|password|expired",
    "/manage/securityquestion/change/success" : "postloginaction|securityquestion|change|success",
    "/manage/username/change" : "manage|username|change",
    "/manage/username/change/success" : "manage|username|change|success",
    "/manage/username/update" : "postloginaction|username|update",
    "/manage/username/update/success" : "postloginaction|username|update|success",
    "/manage/username/validate" : "postloginaction|username|validate",
    "/manage/username/validate/resend" : "postloginaction|username|validate|resend",
    "/manage/username/verify/failure":"manage|username|verify|failure",
    "/manage/username/verify/resend" : "manage|username|verify|resend",
    "/manage/username/verify/success" : "manage|username|verify|success",
    "/register/accountexists" : "register|accountexists",
    "/register/cancel" : "register|cancel",
    "/register/confirm" : "register|confirm",
    "/register/details" : "register|details",
    "/resetpassword/sendmail" : "resetpassword|sendmail",
    "/resetpassword/success" : "resetpassword|success",
    "/syserror" : "syserror",
    "/transferproducts/byphonenumber":"transferproducts|byphonenumber",
    "/transferproducts/challenges" : "transferproducts|challenges",
    "/transferproducts/confirm":"transferproducts|confirm",
    "/transferproducts":"transferproducts",
    "/signin" : "signin",
    "/registrationnotfound" : "registrationnotfound"
}